[[library]]
type="file"
name="log"
path="../log"
includes=["log/log.hpp"]

[[library]]
type="file"
name="sched"
path="../sched"
includes=["sched/sched.hpp"]

[[library]]
type="file"
name="encnet"
path="../encnet"
includes=["encnet/enc_listener.hpp", "encnet/enc_socket.hpp"]

[[library]]
type="file"
name="config"
path="../config"
includes=["config/var.hpp"]
